# Site settings
title: "IndustryResume Blog"
description: "Expert insights and practical tips for STEM PhDs transitioning to industry careers"
baseurl: "/IndustryResume2" # the subpath of your site
url: "https://gauravgoyal355.github.io" # Your GitHub Pages domain
author: "IndustryResume Team"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
logo: /assets/images/logo.png
social:
  name: IndustryResume
  links:
    - https://twitter.com/industryresume
    - https://linkedin.com/company/industryresume

# Blog settings
permalink: /IndustryResume2/blog/:title/
paginate: 10
paginate_path: "/IndustryResume2/blog/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /IndustryResume2/blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "IndustryResume Team"
      show_sidebar: true

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include
include:
  - _pages
