# Site settings
title: "IndustryResume"
description: "Expert resume advice for STEM PhDs transitioning to industry careers. Academic CV conversion, job search strategies, and career guidance for PhD scientists and postdocs."
baseurl: "" # Empty for custom domain
url: "https://industryresume.com" # Your custom domain
author: "IndustryResume Team"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
logo: /assets/images/logo.png
social:
  name: IndustryResume
  links:
    - https://twitter.com/industryresume
    - https://linkedin.com/company/industryresume

# Blog settings
permalink: /blog/:title/
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "IndustryResume Team"
      show_sidebar: true

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include
include:
  - _pages
